# Generated by Django 6.0.5 on 2026-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', help_text='Dietary preference', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_gym_preference',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('gym', 'Gym')], help_text='Preferred workout location', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Workout fitness level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_level', to='main.level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_calories',
            field=models.PositiveIntegerField(default=2000, help_text='Daily calorie target'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yoga_level',
            field=models.ForeignKey(blank=True, help_text='Yoga experience level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoga_level', to='main.level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.ForeignKey(blank=True, help_text='Select your primary fitness goal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
