# Generated by Django 6.0.5 on 2026-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_diet_preference_profile_home_gym_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (1-3 days/week)'), (1.55, 'Moderately active (3-5 days/week)'), (1.725, 'Very active (6-7 days/week)'), (1.9, 'Super active (physical job/twice daily)')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
