# Generated by Django 6.0.5 on 2026-07-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet_preference',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg'), ('Mix', 'Mix')], default='both', help_text='Dietary preference', max_length=10),
        ),
    ]
