# Generated by Django 6.0.5 on 2026-07-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Fitness Level',
                'verbose_name_plural': 'Fitness Levels',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Meal Type',
                'verbose_name_plural': 'Meat Types',
            },
        ),
        migrations.CreateModel(
            name='YogaStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Yoga Style',
                'verbose_name_plural': 'Yoga Styles',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Meal components / dish description')),
                ('total_calories', models.PositiveIntegerField()),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fats_g', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('veg', 'Vegitarian'), ('nonn-veg', 'Non-Vegitarian ')], default='veg', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='food/thumbnails/')),
                ('youtube_link', models.URLField(blank=True, help_text='Recipe video link', null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goal')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mealtype')),
            ],
            options={
                'verbose_name': 'Food / Meal',
                'verbose_name_plural': 'Foods / Meals',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Average duration (minutes)')),
                ('calories_burned_per_minute', models.FloatField(help_text='Avg. calories burned per minute')),
                ('home_gym', models.CharField(choices=[('home', 'Home'), ('gym', 'Gym'), ('both', 'Both')], default='both', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='workouts/thumbnails/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goal')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('calories_burned_per_minute', models.FloatField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='yoga/thumbnails/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goal')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.yogastyle')),
            ],
            options={
                'verbose_name': 'Yoga Session',
                'verbose_name_plural': 'Yoga Sessions',
            },
        ),
    ]
