# Generated by Django 6.0.5 on 2026-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtype',
            options={'verbose_name': 'Meal Type', 'verbose_name_plural': 'Meal Types'},
        ),
        migrations.RemoveField(
            model_name='yoga',
            name='style',
        ),
        migrations.AddField(
            model_name='yoga',
            name='hindi_name',
            field=models.CharField(blank=True, help_text='Hindi name og yoga poses', max_length=120),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegitarian'), ('non-veg', 'Non-Vegitarian ')], default='veg', max_length=10),
        ),
    ]
