# Generated by Django 6.0.5 on 2026-07-13 16:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mealtype_options_remove_yoga_style_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YogaStyle',
        ),
        migrations.AlterModelOptions(
            name='yoga',
            options={'verbose_name': 'Yoga Pose', 'verbose_name_plural': 'Yoga Poses'},
        ),
        migrations.AlterField(
            model_name='yoga',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
