# Generated by Django 6.0.5 on 2026-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_yogastyle_alter_yoga_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoga',
            name='hindi_name',
        ),
        migrations.AddField(
            model_name='yoga',
            name='sanskrit_name',
            field=models.CharField(blank=True, help_text='Sanskrit name of yoga poses', max_length=120),
        ),
    ]
