# Generated by Django 6.0.5 on 2026-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_yoga_hindi_name_yoga_sanskrit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='pose_type',
            field=models.CharField(choices=[('seated', 'Seated'), ('standing', 'Standing'), ('forward-bend', 'Forward-bend'), ('back-bend', 'Back-bend'), ('twist', 'Twist'), ('inversion', 'Inversion'), ('arm-balance', 'Arm-balance'), ('Restorative', 'Restorative'), ('Preparatory', 'Preparatory')], default='', max_length=20),
        ),
    ]
