# Generated by Django 6.0.5 on 2026-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_yoga_pose_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='thumbnail_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='food/thumbnails/'),
        ),
    ]
