# Generated by Django 6.0.5 on 2026-07-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_yoga_thumbnail_link_alter_yoga_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoga',
            name='thumbnail_link',
        ),
        migrations.AlterField(
            model_name='yoga',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
