# Generated by Django 6.0.5 on 2026-07-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_yoga_thumbnail_link_alter_yoga_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
