# Generated by Django 6.0.5 on 2026-07-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_food_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg ')], max_length=10),
        ),
    ]
