# Generated by Django 6.0.5 on 2026-07-15 22:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
